config/routes.rb
Rails.application.routes.draw do
  get 'error_page', to: 'special#error_page' unless Rails.env.production?

  if Rails.env.development?
    mount FRMailer::Preview => 'fr_mail_view'
    mount SubscriptionMailer::Preview => 'subscription_mail_view'
    mount CommentMailer::Preview => 'comment_mail_view'
    mount DocumentMailer::Preview => 'document_mail_view'
  end

  get 'alive' => 'special#alive'
  get 'status', to: 'special#status'

  get '/robots.txt', to: 'special#robots'

  match '/404', to: 'application#not_found', via: :all, as: :not_found
  match '/405', to: 'application#not_authorized', via: :all, as: :not_authorized
  match '/500', to: 'application#server_error', via: :all, as: :server_error

  #
  # Documents
  #

  get 'documents/current',
    to: "document_issues#current",
    as: :current_document_issue

  get 'documents/:year/:month/:day',
    to: "document_issues#show",
    as: :document_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'document_issues/search',
    to: "document_issues#search",
    as: :document_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }

  get 'documents/:document_number/emails/new',
    to: 'documents/emails#new',
    as: :new_document_email

  post 'documents/:document_number/emails',
    to: 'documents/emails#create',
    as: :document_email

  get 'documents/:year/:month/:day/:document_number/:slug',
    to: "documents#show",
    as: :document,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/,
      slug:  /[^\/]+/
    }

  # don't break old urls
  get '/a/:document_number(/:anchor)',
    to: "documents#tiny_url"

  get '/d/:document_number(/:anchor)',
    to: "documents#tiny_url",
    as: :short_document


  #
  # Documents Search
  #

  get 'documents/search',
    to: 'search/documents#show',
    as: 'documents_search'

  with_options(:quiet => true) do |js|
    js.get 'documents/search/count',
      to: 'search/documents#search_count',
      as: 'documents_search_search_count'
  end

  #
  # Public Inspection Documents
  #

  # legacy route that redirects to current
  get 'public-inspection',
    to: 'public_inspection_document_issues#public_inspection',
    as: :public_inspection

  get 'public-inspection/current',
    to: "public_inspection_document_issues#current",
    as: :current_public_inspection_issue

  get 'public-inspection/:year/:month/:day',
    to: "public_inspection_document_issues#show",
    as: :public_inspection_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'public_inspection_issues/search',
    to: "public_inspection_document_issues#search",
    as: :public_inspection_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }


  #
  # Public Inspection Documents Search
  #

  get 'public-inspection/search',
    to: 'search/public_inspection_documents#show',
    as: 'public_inspection_search'

  with_options(:quiet => true) do |js|
    js.get 'public-inspection/search/count',
      to: 'search/public_inspection_documents#search_count',
      as: 'public_inspection_search_count'
  end

  get 'public_inspection_documents/:year/:month/:day/:document_number/:slug',
    to: redirect('/public-inspection/%{document_number}/%{slug}')
  get 'public-inspection/:document_number/:slug',
    to: "public_inspection_documents#show",
    as: :public_inspection_document,
    constraints: {
      slug:  /[^\/]+/
    }

  #
  # Citations
  #

  get 'select-citation/:year/:month/:day/:citation',
    to: 'citations#cfr',
    as: 'select_cfr_citation',
    constraints: {
      citation: /\d+-CFR-\d+(?:\.\d+)?/,
      year: /\d{4}/,
      month: /\d{1,2}/,
      day: /\d{1,2}/
    }

  get 'citation/:volume-FR-:page',
    as: 'citation',
    to: 'citations#fr',
    contraints: {volume: /\d+/, page: /\d+/}

  get 'executive-order/:eo_number',
    as:'executive_order',
    to: 'citations#eo',
    contraints: {eo_number: /\d+/}


  #
  # ESI Routes
  #
  with_options(:quiet => true) do |esi|
    #CALENDAR
    esi.get 'esi/document_issues/:year/:month',
      to: 'document_issues#by_month',
      as: :document_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    esi.get 'esi/public_inspection_issues/:year/:month',
      to: 'public_inspection_document_issues#by_month',
      as: :public_inspection_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    # HEADER
    esi.get '/esi/special/csrf_protection',
      to: 'special#csrf_protection',
      as: :csrf_protection

    esi.get 'special/site_notifications/:identifier',
      to: 'special#site_notifications',
      as: :site_notification

    # READER AIDS
    esi.get 'esi/reader_aids/:section',
      to: 'reader_aids#index_section',
      as: :reader_aids_index_section,
      constraints: {
        section: /(#{ReaderAid::SECTIONS.map{|k,v| k}.join('|')})/
      }


    # FOOTER
    esi.get 'esi/layout/footer',
      to: 'special#footer',
      as: :footer
  end


  #
  # Reader Aids
  #

  get 'reader-aids',
    to: 'reader_aids#index',
    as: :reader_aids

  get 'reader-aids/search',
    to: 'reader_aids#search',
    as: :reader_aids_search

  get 'reader-aids/office-of-the-federal-register-blog',
    to: redirect("reader-aids/office-of-the-federal-register-announcements")

  get 'reader-aids/office-of-the-federal-register-blog/(*all)',
    to: redirect("reader-aids/office-of-the-federal-register-announcements/%{all}")

  get 'reader-aids/:section',
    to: 'reader_aids#section',
    as: :reader_aids_section

  get 'reader-aids/:section/*date/:page',
    to: 'reader_aids#show',
    as: :reader_aid_blog_post,
    contraints: {
      section: ['office-of-the-federal-register-announcements', 'recent-updates']
    }

  get 'reader-aids/:section/:page(/*subpage)',
    to: 'reader_aids#show',
    as: :reader_aid

  get '/policy/continuity-information', to: redirect('https://www.archives.gov/federal-register/write/newsletter/2024-may')


  #
  # Home
  #
  root to: 'special#home'


  #
  # Topics
  #

  get 'topics/suggestions',
    controller: "topics",
    actions: "suggestions",
    as: 'topics_suggestions'

  resources :topics, only: [:index, :show]

  get 'topics/:id/significant.:format',
    :controller => "topics",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_topic'


  #
  # Agencies
  #

  get 'agencies/suggestions',
    controller: "agencies",
    actions: "suggestions",
    as: 'agency_suggestions'

  resources :agencies, only: [:index, :show]

  get 'agencies/:id/significant.:format',
    :controller => "agencies",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_agency'


  #
  # Executive Orders
  #

  get '/executive-orders',
    to: redirect('/presidential-documents/executive-orders')

  get '/executive-orders/:president/:year',
    to: redirect('/presidential-documents/executive-orders/%{president}/%{year}')


  #
  # Presidential Documents
  #

  get '/presidential-documents',
    to: 'presidential_documents#index',
    as: :all_presidential_documents

  get '/presidential-documents/:type',
    to: 'presidential_documents#show',
    as: :presidential_documents,
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }

  get '/presidential-documents/:type/:president/:year',
    to: 'presidential_documents#by_president_and_year',
    as: 'presidential_documents_by_president_and_year',
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }


  #
  # Sections
  #

  get '/:section',
    to: 'sections#show',
    as: :section,
    constraints: {
      section: Regexp.new(Section.slugs.join("|"))
    }

  get 'sections/:id/significant.:format',
    :controller => "sections",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_section'


  #
  # Single Sign On
  #

  get '/auth/sign_in', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out


  #
  # API
  #
  scope "api" do
    namespace :v1 do
      resources :clippings, only: [:index]
    end
  end

  #
  # API Documentation
  #
  get '/developers/documentation/api/v1', to: 'api_documentation#show', as: :api_documentation

  get "/suggestions", to: "suggestions#index", as: :suggestions


  #
  # Suggested searches
  #

  get '/:slug',
    to: 'suggested_searches#show',
    as: :suggested_search,
    constraints: SuggestedSearchContraint.new


  #
  # FR Index
  #

  get '/index/:year',
    controller: "indexes",
    action: "year",
    as: 'index_year',
    constraints: {
      year: /(19|20)\d{2}/
    }

  get '/index/:year/:agency_slug',
    controller: "indexes",
    action: "year_agency",
    as: 'year_agency_index',
    constraints: {
      year: /(19|20)\d{2}/
    }

  resources :zendesk_tickets, only: [:create]

  #
  # My FR
  #

  scope 'my' do
    root :to => "clippings#index",
         :as => :my_root

    resources :clippings do
      collection do
        post 'bulk_create'
      end
    end

    get 'folders/my-clippings', to: redirect('/my/clippings')
    resources :folders
    resources :folder_clippings do
      collection do
        post 'delete'
      end
    end

    resources :comments, :only => [:index] do
      collection do
        post :persist_for_login
      end
    end

    get 'documents/:document_number/comments/new' => 'comments#new',
     :as => :new_comment
    post 'documents/:document_number/comments' => 'comments#create',
     :as => :comment

    resource :comment_publication_notifications,
      :only => [:create, :destroy]

app/models/search_details/document.rb
class SearchDetails::Document < SearchDetails::Base
  def response
    @response ||= FederalRegister::DocumentSearchDetails.search(conditions: conditions)
  end
end

app/controllers/documents/emails_controller.rb
class Documents::EmailsController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  layout false

  def new
    @document = Document.find(params[:document_number])

    raise ActiveRecord::RecordNotFound unless @document

    @document_email = EntryEmail.new
    @document_email.document_number = @document.document_number
  end

  def create
    @document = Document.find(params[:document_number])
    @document_email = EntryEmail.new(document_email_params)
    @document_email.document_number = @document.document_number
    @document_email.remote_ip = request.remote_ip

    if (!@document_email.requires_captcha? || 
      (params['g-recaptcha-response'].present? &&
      verify_recaptcha(model: @document_email)
    )) && @document_email.save
      render plain: '<div class="flash-message success">Success! Your email will be sent momentarily.</div>', status: 200
    else
      render action: :new, status: 400
    end
  end

  private

  def document_email_params
    params.require(:entry_email).permit(
      :sender,
      :send_me_a_copy,
      :recipients,
      :message
    )
  end
end

app/controllers/documents/search_controller.rb
class Documents::SearchController < SearchController
  skip_before_filter :authenticate_user!

  def show
    @presenter = SearchPresenter.new(params)
    @search = @presenter.search
    if illegal_conditions_present?
      redirect_to documents_search_path(
        shared_search_params.merge(
          conditions: clean_conditions(@search.valid_conditions),
          format: params[:format]
        )
      )
    else
      respond_to do |wants|
        wants.html
        wants.rss do
          @feed_name = "Federal Register: Search Results"
          @feed_description = "Federal Register: Search Results"
          @entries = @search.results
          render :template => 'documents/index.rss.builder'
        end
        wants.csv do
          redirect_to "http://www.federalregister.gov/api/v1/articles.csv?" + 
            shared_search_params.merge(conditions: params[:conditions]).to_param
        end
        wants.json do
          redirect_to "http://www.federalregister.gov/api/v1/articles.json?" + 
            shared_search_params.merge(conditions: params[:conditions]).to_param
        end
      end
   end
  end
  
  def facets
    cache_for 1.day
    @presenter = SearchFacetPresenter.new(params)
    
    if params[:all]
      render :partial => "search/facet", :collection => @presenter.facets, :as => :facet
    else
      render :partial => "search/facets", :locals => {:facets => @presenter.facets, :name => @presenter.facet_name}, :layout => false
    end
  end
  
  def suggestions
    cache_for 1.day
    @presenter = SearchPresenter.new(params)
    @search = @presenter.search
    @search_details = @search.search_details
    # RW: necessary?  called from suggestion.html.erb, may have to add when PI is complete
    #if params[:conditions]
    #  @public_inspection_document_search = PublicInspectionDocumentSearch.new_if_possible(
    #    :conditions => @search.valid_conditions
    #  )
    #end
    render :layout => false
  end

  def help
    cache_for 1.day
    if params[:no_layout]
      render :layout => false
    else
      render
    end
  end

  private
  def shared_search_params
    params.slice(:page, :order, :fields, :per_page)
  end

  def illegal_conditions_present?
    blank_conditions?(params[:conditions]) || ((params[:conditions].try(:keys) || []) - @search.valid_conditions.keys).present?
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include DocumentLookup

  skip_before_action :authenticate_user!
  before_action :find_document

  def show
    cache_for 1.day

    respond_to do |wants|
      wants.html do
        if @document.is_a?(Document)
          @document = DocumentDecorator.decorate(@document)

          if document_path(@document) == request.path
            render
          else
            redirect_to document_path(@document)
          end
        elsif @document.is_a?(PublicInspectionDocument)
          redirect_to @document.html_url
        end
      end

      wants.json do
        redirect_to document_api_url(@document, {format: :json})
      end

      wants.pdf do
        if @document.is_a?(Document) && @document.pdf_url.present?
          redirect_to @document.pdf_url, status: :moved_permanently
        elsif @document.html_url
          redirect_to @document.html_url
        end
      end
    end
  end

  def tiny_url
    cache_for 1.day

    respond_to do |wants|
      wants.html do
        url = @document.html_url

        # the document endpoints can return more than one document
        # if the document number is comma separated in these cases there is
        # no one place to redirect to
        raise ActiveRecord::RecordNotFound unless url

        if params[:anchor].present?
          url += '#' + params[:anchor]
        end

        status = @document.is_a?(Document) ? :moved_permanently : :found # 301 : 302

        redirect_to url, status: status
      end

      wants.pdf do
        if @document.is_a?(Document) && @document.pdf_url.present?
          redirect_to @document.pdf_url, status: :moved_permanently
        elsif @document.html_url
          redirect_to @document.html_url
        else
        end
      end
    end
  end

end

app/controllers/search/documents_controller.rb
class Search::DocumentsController < ApplicationController
  include ConditionsHelper
  before_action :load_presenter, except: [:help]
  skip_before_action :authenticate_user!

  DEFAULT_CSV_MAXIMUM_PER_PAGE = 1000
  def show
    cache_for 1.day

    if valid_search?
      respond_to do |wants|
        wants.html do
          if disallowed_subscription_params?
            @subscription_search = SearchPresenter::Document.new(subscription_params.permit!.to_h).search
          else
            @subscription_search = @search
          end
        end

        wants.csv do
          redirect_to documents_search_api_path(
            shared_search_params.merge(
              conditions: params[:conditions],
              per_page: params[:per_page] || DEFAULT_CSV_MAXIMUM_PER_PAGE
            ),
            format: :csv
          )
        end

        wants.json do
          redirect_to documents_search_api_path(
            shared_search_params.merge(conditions: params[:conditions]),
            format: :json
          )
        end
      end
    else
      redirect_to clean_search_path
    end
  end

  def help
    redirect_to reader_aids_search_help_url
  end

  def search_count
    cache_for 1.day
    valid_conditions = Search::Document.new(params.permit!.to_h).valid_conditions

    render json: {
      count: ::Document.search_metadata(conditions: valid_conditions).count,
      url: documents_search_path(conditions: valid_conditions)
    }
  rescue FederalRegister::Client::BadRequest => e
    render json: {
      count: 0,
      url: documents_search_path(conditions: valid_conditions)
    }
  end

  private

  def load_presenter
    @presenter = SearchPresenter::Document.new(params.permit!.to_h)
    @search = @presenter.search
  end

  DISALLOWED_SUBSCRIPTION_SEARCH_PARAMS = 'publication_date', 'effective_date', 'comment_date'
  def subscription_params
    ActionController::Parameters.new({
      conditions: params[:conditions].except(*DISALLOWED_SUBSCRIPTION_SEARCH_PARAMS)
    })
  end

  def disallowed_subscription_params?
    params[:conditions] &&
    DISALLOWED_SUBSCRIPTION_SEARCH_PARAMS.any?{|x| params[:conditions] && params[:conditions][x]}
  end

end

app/views/documents/_add_to_clipboard.html.erb
<%= form_tag(clippings_path, method: :post, class: "add_to_clipboard") do %>
  <%= hidden_field_tag(:document_number, document.document_number, id: "clipping_document_number") %>
  <%= submit_tag "Add to clipboard" %>
<% end %>

app/views/documents/_comment_count_by_docket.html.erb
<div class="comment-count-by-docket <%= 'hidden' unless local_assigns[:visible] %>">
  <% dockets = document.
    regs_dot_gov_documents_once_accepted_comments.
    map(&:docket).uniq %>

  <p>
    <%= "#{pluralize(document.comment_count, "comment")}
    #{document.comment_count == 1 ? "has" : "have"}
    been received at Regulations.gov." %>
  </p>

  <p>
    Agencies review all submissions and may choose to redact, or withhold,
    certain submissions (or portions thereof). Submitted comments may not be
    available to be read until the agency has approved them.
  </p>

  <div class="table-container">
    <table>
      <thead>
        <th>Docket Title</th>
        <th>Document ID</th>
        <th class="text-center">Comments</th>
        <th></th>
      </thead>
      <tbody>
        <% document.regs_dot_gov_documents_once_accepted_comments.each do |doc| %>
          <tr>
            <td>
              <%= doc.docket.try(:title) %>
            </td>
            <td>
              <%= link_to doc.id,
                "https://www.regulations.gov/document/#{doc.id}",
                target: "_blank" %>
            </td>
            <td>
              <%= link_to doc.comment_count,
                "https://www.regulations.gov/document/#{doc.id}/comment",
                target: "_blank"  %>
            </td>
            <td>
              <% if doc.updated_at %>
                <%= tooltip_icon "info-circle",
                  "data-title" => "Last synced with regulations.gov at #{doc.updated_at.to_s(:datetime)}",
                  "data-placement" => "left" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/documents/_corrections.html.erb
<% if document.correction_of %>
  <%= render partial: 'shared/notice_bar', locals: {
    css_class: 'correction-of',
    message_text: (document.republication? ? "This document is a corrected republication of a document published on #{document.correction_of_document.publication_date}." : "This document is a correction of a document that was published on #{document.correction_of_document.publication_date}."),
    link_text: 'View Uncorrected Document',
    link_url: document.correction_of_document.html_url
  } %>
<% end %>

<% if document.corrections.present? %>
  <% document.corrected_documents.each do |correction| %>
    <%= render partial: 'shared/notice_bar', locals: {
      css_class: 'correction',
      message_text: (correction.republication? ? "This document has been corrected and republished on #{correction.publication_date}" : "This document was corrected by a document published on #{correction.publication_date}."),
      link_text: "View #{correction.republication? ? "Republication" : "Correction"}",
      link_url: correction.html_url
    } %>
  <% end %>
<% end %>

app/views/documents/_formal_comment_bar.html.erb
<div id="comment-bar" class="document-notice-bar comment"
  data-document-number="<%= document.document_number %>"
  data-reggov-agency="<%= document.regulations_dot_gov_agency_id %>"
  data-reggov-comment-url="<%= document.comment_url %>"
  data-comments-close-on="<%= document.comments_close_on %>"
  data-comment-days-remaining="<%= document.comment_period_days_remaining %>"
  data-comment-period-open="<%= document.document_comment_period_open? %>"
  data-republished-document-comment-url="<%= document.republished_document_comment_url %>"
  data-reg-gov-participating-agency="<%= document.participating_agency? %>">
  <p>
    <%= fr_icon 'Chat' %>
    <% if document.document_comment_period_open? && !document.comment_close_date_discrepancy_between_mods_and_regulations_dot_gov? %>
      This document has a comment period that ends <%= document.comment_period_days_remaining %>.
      (<%= document.comments_close_on %>)
    <% else %>
      Comments on this document are being accepted at Regulations.gov.
    <% end %>

    <%= document.formal_comment_link %>
  </p>
</div>

<% if document.has_comments? %>
  <div class="reg-gov-comments-count">
    <%= link_to pluralize(document.comment_count, "comment"), "#",
      class: "deploy-comment-sidebar-js" %>
    received.

    <%= document.posted_comments_link %>
  </div>
<% end %>

<%= render partial: "comment_wrapper",
  locals: {
    document: document,
    multi_agency_comment_submission: document.regs_dot_gov_documents_accepting_comments.count > 1
  } %>

app/views/documents/_grouped_by_topic.html.erb
<% topics.each do |topic| %>
  <li>
    <h3 id='<%=topic.name%>'><%= topic.name %> <span class='top'><%= link_to 'back to top', "#top" %></h3>
    <ul>
    <% documents.select{|e| e.topic_ids.include?(topic.id)}.group_by(&:publication_date).each do |pub_date, documents| %>
      <li>
        <h4><%= link_to pub_date.to_formatted_s(:pretty), document_issue_path(pub_date) %></h4>
        <ul class="indent raquo">
          <% documents.each do |document| %>
            <li><%= link_to truncate_words(document.title, :length => 100), document_issue_path(document) %></li>
          <% end %>
        </ul>
      </li>
    <% end %>
    <% if documents.select{|e| e.topic_ids.include?(topic.id)}.empty? %>
      <li>No documents exist with this topic in the most recent 100 documents</li>
    <% end %>
    </ul>
  </li>
<% end %>

app/views/documents/_list.html.erb
<% list_type ||= nil %>
<%= render partial: 'documents/list_header', locals: {
  documents: documents
} %>

<% if list_type %>
  <% if list_type == 'topic' %>
    <%= render partial: 'documents/grouped_by_topic', locals: {
      documents: documents,
      topics: topics
    } %>
  <% elsif list_type == 'agency' %>
    <%= render partial: 'documents/grouped_by_date', locals: {
      documents: documents
    } %>
  <% end %>
<% else %>
  <%= render partial: 'documents/grouped_by_date', locals: {
    documents: documents
  }%>
<% end %>

app/views/documents/_list_header.html.erb
<div class="title_bar" id="recent_articles">
  <h2><span class="small_stack">Listing<span> Of <%= documents.count < 50 ? 'All' : "50" %> </span></span>Recent Documents</h2>
  <% if false && documents.count > 50 %>
    <span class="actions"><%= link_to "view all", entries_search_path(search_params) %></span>
  <% end %>
</div>

app/views/documents/_metadata_content_area.html.erb
<div id="metadata_content_area" class="metadata-content-area">
  <h1 class="<%= document.title_class %>">
    <%= document.title %>
  </h1>

  <div class="metadata_share_bar">
    <p class="metadata">
      <%= document.metadata_description %>
    </p>

    <div class="document-clipping-actions"
      data-document-number="<%= document.document_number %>">
      <ul>
        <li class="clip-for-later">
          <%= semantic_form_for :document,
            url: clippings_path,
            authenticity_token: false,
            html: {
              method: :post,
              class: "add-to-clipboard"
            } do |f| %>

            <%= f.inputs do %>
              <%= f.input :document_number,
                as: :hidden,
                value: document.document_number %>
            <% end %>

            <%= f.actions do %>
              <%= f.action :submit, label: 'Add to clipboard' %>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>

  <%= render(
    partial: "formal_comment_bar", locals: {
      document: document,
      docket_info: document.regulations_dot_gov_info
    }
  ) if document.accepting_comments? %>

  <%= render partial: "corrections", locals: {document: document} if document.corrections? %>
</div>

app/views/documents/_page_content.html.erb
<%= modal(:basic,
    footer: false,
    header: false,
    modal_class: 'document-table-modal',
    modal_id: 'bootstrap-table-modal',
) do %>
  <%= fr_content_box(
    FrBox.build(document.fr_content_box_type, document.fr_content_box_options)
  ) do %>
  <% end %>
<% end %>

<div class="doc-content with-utility-nav wide-utility-nav">
  <div id="print-only-document-details">
    <ul>
      <%= render partial: 'documents/utility_nav/document_details', locals: {
        document: @document
      } %>

      <% if document.executive_order_number.present? %>
        <%= render partial: 'documents/utility_nav/executive_order_data', locals: {
            document: @document
          } %>
      <% end %>
    </ul>
  </div>

  <div class="content-nav-wrapper">
    <%= render partial: "utility_nav", locals: {
      document: document,
      docket_info: document.regulations_dot_gov_info
    } %>
  </div>

  <div class="content-col">
    <%= fr_content_box(
      FrBox.build(document.fr_content_box_type, document.fr_content_box_options)
    ) do %>
      <% if document.official? %>
        <span class="icon-fr2 icon-fr2-NARA1985Seal doc-background"></span>
      <% end %>

      <div id="fulltext_content_area" class="doc-content-area"
        data-short-url="<%= short_document_url(document) %>">

        <div class="citation-target-icon cj-fancy-tooltip"
          data-tooltip="Click to copy a short url for this paragraph"
          data-short-url="<%= short_document_url(document) %>">
          <%= fr_icon 'bookmark' %>
        </div>
        <div class="citation-target-background"></div>

        <% if document.full_text_available? %>
          <%= document.full_text %>
        <% else %>
          <p>
            <% if document.pdf_available?  %>
              The full text of this document is currently available in
              <%= link_to 'PDF format', document.pdf_url, target: :blank %>.
            </p>
            <p>
            <% end %>

            The full text of this document is
            <%= document.pdf_available? ? 'also available' : 'currently only available' %>
            in <%= link_to 'a basic text format', document.gpo_raw_text_url, target: :blank %>.
          </p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/documents/_table_of_contents_doc_details.html.erb
<div class='toc-documents'>
  <% documents.each do |document| %>
    <% document = @presenter.lookup_document(document) %>
    <h7><%= link_to(subject, document.html_url) %></h7>
    <div class="row no-bottom-margin">
      <ul class="col-xs-2 col-md-2 test_font_style">
        <li> <%= link_to "<span class='icon-fr2 icon-fr2-doc-pdf'> PDF <span>".html_safe, document.pdf_url %> </li>
        <li>(<%= pluralize(page_count(document), "Page") %>)</li>
      </ul>
      <ul class="col-xs-3 col-md-3 test_font_style">
        <li><%= "FR Document: #{document.document_number}" %></li>
        <li><%= document_page_range(document)%></li>
      </ul>
    </div>
  <% end %>
</div>