config/routes.rb
Rails.application.routes.draw do
  get 'error_page', to: 'special#error_page' unless Rails.env.production?

  if Rails.env.development?
    mount FRMailer::Preview => 'fr_mail_view'
    mount SubscriptionMailer::Preview => 'subscription_mail_view'
    mount CommentMailer::Preview => 'comment_mail_view'
    mount DocumentMailer::Preview => 'document_mail_view'
  end

  get 'alive' => 'special#alive'
  get 'status', to: 'special#status'

  get '/robots.txt', to: 'special#robots'

  match '/404', to: 'application#not_found', via: :all, as: :not_found
  match '/405', to: 'application#not_authorized', via: :all, as: :not_authorized
  match '/500', to: 'application#server_error', via: :all, as: :server_error

  #
  # Documents
  #

  get 'documents/current',
    to: "document_issues#current",
    as: :current_document_issue

  get 'documents/:year/:month/:day',
    to: "document_issues#show",
    as: :document_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'document_issues/search',
    to: "document_issues#search",
    as: :document_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }

  get 'documents/:document_number/emails/new',
    to: 'documents/emails#new',
    as: :new_document_email

  post 'documents/:document_number/emails',
    to: 'documents/emails#create',
    as: :document_email

  get 'documents/:year/:month/:day/:document_number/:slug',
    to: "documents#show",
    as: :document,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/,
      slug:  /[^\/]+/
    }

  # don't break old urls
  get '/a/:document_number(/:anchor)',
    to: "documents#tiny_url"

  get '/d/:document_number(/:anchor)',
    to: "documents#tiny_url",
    as: :short_document


  #
  # Documents Search
  #

  get 'documents/search',
    to: 'search/documents#show',
    as: 'documents_search'

  with_options(:quiet => true) do |js|
    js.get 'documents/search/count',
      to: 'search/documents#search_count',
      as: 'documents_search_search_count'
  end

  #
  # Public Inspection Documents
  #

  # legacy route that redirects to current
  get 'public-inspection',
    to: 'public_inspection_document_issues#public_inspection',
    as: :public_inspection

  get 'public-inspection/current',
    to: "public_inspection_document_issues#current",
    as: :current_public_inspection_issue

  get 'public-inspection/:year/:month/:day',
    to: "public_inspection_document_issues#show",
    as: :public_inspection_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'public_inspection_issues/search',
    to: "public_inspection_document_issues#search",
    as: :public_inspection_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }


  #
  # Public Inspection Documents Search
  #

  get 'public-inspection/search',
    to: 'search/public_inspection_documents#show',
    as: 'public_inspection_search'

  with_options(:quiet => true) do |js|
    js.get 'public-inspection/search/count',
      to: 'search/public_inspection_documents#search_count',
      as: 'public_inspection_search_count'
  end

  get 'public_inspection_documents/:year/:month/:day/:document_number/:slug',
    to: redirect('/public-inspection/%{document_number}/%{slug}')
  get 'public-inspection/:document_number/:slug',
    to: "public_inspection_documents#show",
    as: :public_inspection_document,
    constraints: {
      slug:  /[^\/]+/
    }

  #
  # Citations
  #

  get 'select-citation/:year/:month/:day/:citation',
    to: 'citations#cfr',
    as: 'select_cfr_citation',
    constraints: {
      citation: /\d+-CFR-\d+(?:\.\d+)?/,
      year: /\d{4}/,
      month: /\d{1,2}/,
      day: /\d{1,2}/
    }

  get 'citation/:volume-FR-:page',
    as: 'citation',
    to: 'citations#fr',
    contraints: {volume: /\d+/, page: /\d+/}

  get 'executive-order/:eo_number',
    as:'executive_order',
    to: 'citations#eo',
    contraints: {eo_number: /\d+/}


  #
  # ESI Routes
  #
  with_options(:quiet => true) do |esi|
    #CALENDAR
    esi.get 'esi/document_issues/:year/:month',
      to: 'document_issues#by_month',
      as: :document_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    esi.get 'esi/public_inspection_issues/:year/:month',
      to: 'public_inspection_document_issues#by_month',
      as: :public_inspection_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    # HEADER
    esi.get '/esi/special/csrf_protection',
      to: 'special#csrf_protection',
      as: :csrf_protection

    esi.get 'special/site_notifications/:identifier',
      to: 'special#site_notifications',
      as: :site_notification

    # READER AIDS
    esi.get 'esi/reader_aids/:section',
      to: 'reader_aids#index_section',
      as: :reader_aids_index_section,
      constraints: {
        section: /(#{ReaderAid::SECTIONS.map{|k,v| k}.join('|')})/
      }


    # FOOTER
    esi.get 'esi/layout/footer',
      to: 'special#footer',
      as: :footer
  end


  #
  # Reader Aids
  #

  get 'reader-aids',
    to: 'reader_aids#index',
    as: :reader_aids

  get 'reader-aids/search',
    to: 'reader_aids#search',
    as: :reader_aids_search

  get 'reader-aids/office-of-the-federal-register-blog',
    to: redirect("reader-aids/office-of-the-federal-register-announcements")

  get 'reader-aids/office-of-the-federal-register-blog/(*all)',
    to: redirect("reader-aids/office-of-the-federal-register-announcements/%{all}")

  get 'reader-aids/:section',
    to: 'reader_aids#section',
    as: :reader_aids_section

  get 'reader-aids/:section/*date/:page',
    to: 'reader_aids#show',
    as: :reader_aid_blog_post,
    contraints: {
      section: ['office-of-the-federal-register-announcements', 'recent-updates']
    }

  get 'reader-aids/:section/:page(/*subpage)',
    to: 'reader_aids#show',
    as: :reader_aid

  get '/policy/continuity-information', to: redirect('https://www.archives.gov/federal-register/write/newsletter/2024-may')


  #
  # Home
  #
  root to: 'special#home'


  #
  # Topics
  #

  get 'topics/suggestions',
    controller: "topics",
    actions: "suggestions",
    as: 'topics_suggestions'

  resources :topics, only: [:index, :show]

  get 'topics/:id/significant.:format',
    :controller => "topics",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_topic'


  #
  # Agencies
  #

  get 'agencies/suggestions',
    controller: "agencies",
    actions: "suggestions",
    as: 'agency_suggestions'

  resources :agencies, only: [:index, :show]

  get 'agencies/:id/significant.:format',
    :controller => "agencies",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_agency'


  #
  # Executive Orders
  #

  get '/executive-orders',
    to: redirect('/presidential-documents/executive-orders')

  get '/executive-orders/:president/:year',
    to: redirect('/presidential-documents/executive-orders/%{president}/%{year}')


  #
  # Presidential Documents
  #

  get '/presidential-documents',
    to: 'presidential_documents#index',
    as: :all_presidential_documents

  get '/presidential-documents/:type',
    to: 'presidential_documents#show',
    as: :presidential_documents,
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }

  get '/presidential-documents/:type/:president/:year',
    to: 'presidential_documents#by_president_and_year',
    as: 'presidential_documents_by_president_and_year',
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }


  #
  # Sections
  #

  get '/:section',
    to: 'sections#show',
    as: :section,
    constraints: {
      section: Regexp.new(Section.slugs.join("|"))
    }

  get 'sections/:id/significant.:format',
    :controller => "sections",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_section'


  #
  # Single Sign On
  #

  get '/auth/sign_in', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out


  #
  # API
  #
  scope "api" do
    namespace :v1 do
      resources :clippings, only: [:index]
    end
  end

  #
  # API Documentation
  #
  get '/developers/documentation/api/v1', to: 'api_documentation#show', as: :api_documentation

  get "/suggestions", to: "suggestions#index", as: :suggestions


  #
  # Suggested searches
  #

  get '/:slug',
    to: 'suggested_searches#show',
    as: :suggested_search,
    constraints: SuggestedSearchContraint.new


  #
  # FR Index
  #

  get '/index/:year',
    controller: "indexes",
    action: "year",
    as: 'index_year',
    constraints: {
      year: /(19|20)\d{2}/
    }

  get '/index/:year/:agency_slug',
    controller: "indexes",
    action: "year_agency",
    as: 'year_agency_index',
    constraints: {
      year: /(19|20)\d{2}/
    }

  resources :zendesk_tickets, only: [:create]

  #
  # My FR
  #

  scope 'my' do
    root :to => "clippings#index",
         :as => :my_root

    resources :clippings do
      collection do
        post 'bulk_create'
      end
    end

    get 'folders/my-clippings', to: redirect('/my/clippings')
    resources :folders
    resources :folder_clippings do
      collection do
        post 'delete'
      end
    end

    resources :comments, :only => [:index] do
      collection do
        post :persist_for_login
      end
    end

    get 'documents/:document_number/comments/new' => 'comments#new',
     :as => :new_comment
    post 'documents/:document_number/comments' => 'comments#create',
     :as => :comment

    resource :comment_publication_notifications,
      :only => [:create, :destroy]

app/models/subscription.rb
class Subscription < ApplicationRecord
  default_scope { where(environment: Rails.env) }

  before_create :generate_token

  attr_accessor :search_conditions, :search_type

  belongs_to :mailing_list
  belongs_to :comment

  validates_presence_of :requesting_ip, :mailing_list, :environment

  module MailingListAutobuilder
    def mailing_list
      if super.nil?
        klass = search_type == 'PublicInspectionDocument' ? MailingList::PublicInspectionDocument : MailingList::Document
        self.search_conditions ||= {}
        self.mailing_list = klass.find_by_parameters(search_conditions) || klass.new(:parameters => search_conditions)
      else
        super
      end
    end
  end
  prepend MailingListAutobuilder

  def self.not_delivered_on(date)
    where("subscriptions.last_issue_delivered IS NULL OR subscriptions.last_issue_delivered < ?", date)
  end

  def self.not_delivered_for(document_numbers)
    where("subscriptions.last_documents_delivered_hash IS NULL OR subscriptions.last_documents_delivered_hash != ?",
      Digest::MD5.hexdigest( Array(document_numbers).sort.join(',') )
    )
  end

  def public_inspection_search_possible?
    Search::PublicInspection.new(search_conditions).valid_search?
  end

  def to_param
    token
  end

  def user
    @user ||= User.find(user_id)
  end

  def active?
    unsubscribed_at.nil? && deleted_at.nil?
  end

  def unsubscribe!
    unless self.unsubscribed_at
      self.unsubscribed_at = Time.current
      self.save!
    end
  end
  alias_method :suspend!, :unsubscribe!

  def activate!
    self.unsubscribed_at = nil
    self.save!
  end

  def public_inspection?
    mailing_list.class == MailingList::PublicInspectionDocument
  end

  private

  def generate_token
    self.token = SecureRandom.hex(20)
  end

  def self.document_subscriptions
    includes(:mailing_list).
    where(mailing_lists: {type: "MailingList::Document"})
  end

  def self.pi_subscriptions
    includes(:mailing_list).
    where(mailing_lists: {type: "MailingList::PublicInspectionDocument"})
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  with_options(only: [
    :new, :create,
    :confirmation_sent, :confirm, :confirmed,
    :activate, :suspend,
    :unsubscribe, :unsubscribed, :destroy
  ]) do |during_creation|
    during_creation.skip_before_action :authenticate_user!
  end

  before_action :refresh_current_user, only: :index
  skip_before_action :verify_authenticity_token, only: :suspend

  def index
    @subscriptions = SubscriptionDecorator.decorate_collection(
      current_user.subscriptions.order("subscriptions.created_at DESC")
    )
    @document_subscription_count = current_user.subscriptions.document_subscriptions.count
    @pi_subscription_count = current_user.subscriptions.pi_subscriptions.count
  end

  def create
    @subscription = Subscription.new(subscription_params)

    @subscription.requesting_ip = request.remote_ip
    @subscription.environment = Rails.env

    if user_signed_in?
      @subscription.user_id = current_user.id
    end

    if @subscription.save
      if user_signed_in?
        if current_user.confirmed?
          if verified_request?
            flash[:notice] = I18n.t('subscriptions.save.success', title: @subscription.mailing_list.title)
          else
            session[:subscription_notice] = I18n.t('subscriptions.save.success', title: @subscription.mailing_list.title)
          end
        else
          if verified_request?
            flash[:warning] = I18n.t('subscriptions.save.unconfirmed')
          else
            session[:subscription_warning] = I18n.t('subscriptions.save.unconfirmed')
          end
        end

        redirect_to subscriptions_url
      else
        session[:subscription_token] = @subscription.token

        redirect_to sign_in_url(
          nil,
          {notice: I18n.t('subscriptions.save.sign_in_required') }
        )
      end
    else
      Honeybadger.notify(
        error_class: 'Subscription::Invalid',
        error_message: 'Unable to create subscripton',
        context: {
          subscription: @subscription.attributes,
          errors: @subscription.errors.messages
        }
      )

      raise ActiveRecord::RecordInvalid
    end
  end

  def unsubscribe
    @subscription = Subscription.find_by_token!(params[:id])
  end

  def activate
    subscription = Subscription.find_by_token!(params[:id])
    subscription.activate!

    render json: {unsubscribe_url: suspend_subscription_path(subscription.token)}
  end

  def suspend
    subscription = Subscription.find_by_token!(params[:id])
    subscription.suspend!

    if params[:skip_email]
      render json: {resubscribe_url: activate_subscription_path(subscription.token)}
    else
      SubscriptionMailer.unsubscribe_notice(subscription).deliver
      redirect_to unsubscribed_subscriptions_url
    end
  end

  def destroy
    @subscription = Subscription.find_by_token!(params[:id])
    public_inspection_document = @subscription.public_inspection?
    @subscription.destroy
    render json: {publicInspectionDocument: public_inspection_document}
  end

  def unsubscribed
  end

  def subscription_params
    params.require(:subscription).permit(
      :search_type,
      search_conditions: {}
    )
  end
end

app/helpers/subscription_helper.rb
module SubscriptionHelper

  def status_for_subscription(subscription)
    [ content_tag(:dt, 'Status:', :class => subscription.active? ? 'unsubscribe_link' : 'resubscribe_link'),
      content_tag(:dd) do
        content_tag(:span, subscription.active? ? 'active' : 'inactive', :class =>  subscription.active? ? 'active' : 'inactive')
      end
    ].join("\n").html_safe
  end

  def subscribe_box(search_conditions={}, options={})
    render partial: 'components/subscribe_box', locals: {
      options: options,
      search_conditions: search_conditions
    }
  end

  def subscribe_link(search_conditions={}, options={})
    if options[:custom_path]
      path = options[:custom_path]
    else
      path = ''
    end

    link_text = []
    link_text << fr_icon('message') unless options[:rss_only]
    link_text << fr_icon('rss')
    link_text << (options[:rss_only] ? "Subscribe via RSS" : "Subscribe")

    link_to(path, class: "subscription subscription_action #{options[:class]} #{'rss-only' if options[:rss_only]}") do
      link_text.join(" ").html_safe
    end
  end
end

app/views/subscriptions/_subscription_list_item.html.erb
<li data-subscription-id="<%= subscription.id %>"
  data-doc-type="<%= subscription.type.underscore.dasherize %>">

  <%= fr_icon subscription.icon_class, class: 'cj-tooltip',
    data: {
      tooltip: subscription.display_type,
      'tooltip-gravity' => 'w'
    } %>

  <div class="search_data">
    <div class="title">
      <%= link_to subscription.mailing_list.title,
        subscription.search_path %>
    </div>
    <dl class="metadata" class="col-1">
      <dt class="subscription_date">Subscription Started:</dt>
      <dd><%= subscription.subscribed_on %></dd>

      <dt class="pub_date">Last Delivered On:</dt>
      <dd><%= subscription.last_delivered_on %></dd>

      <dt class="pub_date">Delivery Count:</dt>
      <dd><%= subscription.delivery_count %></dd>
    </dl>

    <dl class="metadata" class="col-2">
    </dl>
    <dl class="metadata" id="col-3">
    </dl>
  </div>

  <div class="subscription_data">
    <dl class="metadata">
      <dt class="<%= subscription.active? ? 'unsubscribe_link' : 'resubscribe_link' %>">Status:</dt>
      <% if subscription.active? %>
        <dd>
          <span class='active'>active</span> :
          <%= link_to "suspend", suspend_subscription_path(subscription.token, skip_email: true) , class: 'unsubscribe' %>
        </dd>
      <% else %>
        <dd>
          <span class='inactive'>inactive</span> :
          <%= link_to "re-activate", activate_subscription_path(subscription.token) , class: 'resubscribe' %>
        </dd>
      <% end %>
      <dd>
        <%= link_to "delete", subscription_path(subscription.token),
              class: 'confirm-subscription-destroy-js',
              data: {
                'subscription-id': subscription.id
              } %>
      </dd>

      <dt>Other Formats:</dt>
      <dd class="rss_link">
        <% if subscription.type == "PublicInspectionDocument" %>
          <%= link_to "RSS", public_inspection_search_api_url(
            subscription.search_params, format: :rss
          ) %>
        <% else %>
          <%= link_to "RSS", documents_search_api_path(
            subscription.search_params, format: :rss
          ) %>
        <% end %>
      </dd>

      <% unless subscription.type == "PublicInspectionDocument" %>
        <dd class="csv_link">
          <%= link_to "CSV/Excel", documents_search_api_path(
            subscription.search_params, format: :csv
          ) %>
        </dd>
      <% end %>

      <% if subscription.comment.present? %>
        <dt>Related Document:</dt>
        <dd>
          You commented on <br>
          <%= link_to subscription.comment.document.document_number,
            subscription.comment.document.html_url,
            class: "cj-tooltip commented-on-document",
            data: {
              tooltip: subscription.comment.document.title,
              :"data-tooltip-gravity" => 'e',
              :"data-tooltip-class" => 'commented-on-document'
            } %>

            <br>

            <span class="cj-tooltip"
              data-tooltip="Your comment tracking number"
              data-tooltip-gravity="e">
              (<%= subscription.comment.tracking_number_link %>)
            </span>
          </dd>
      <% end %>
    </dl>
  </div>
</li>

app/views/subscriptions/_subscription_metadata_bar.html.erb
<div class="subscription_metadata_bar">
  <ul>
    <li>
      Document Subscriptions:
      <span class="document_subscription_on_page_count doc-count-js">
        <%= document_subscription_count %>
      </span>
    </li>

    <li>
      Public Inspection Subscriptions:
      <span class="pi_subscription_on_page_count pi-doc-count-js">
        <%= pi_subscription_count %>
      </span>
    </li>
  </ul>
</div>

app/views/subscriptions/index.html.erb
<% page_title "MyFR :: Subscriptions" %>
<% make_layout_fixed_width %>

<% title header_class: 'my-subscriptions' do %>
  <%= fr_icon 'message_open' %>
  My Subscriptions
<% end %>

<%= content_tag(:div, flash[:notice], class: 'flash notice')   if flash[:notice] %>
<%= content_tag(:div, flash[:error], class: 'flash error')     if flash[:error]  %>
<%= content_tag(:div, flash[:warning].html_safe, class: 'flash warning') if flash[:warning]  %>

<h2 class="subscription title">
  <%= fr_icon 'message_open' %>
  My Subscriptions
</h2>

<% if current_user.confirmed? %>
  <%= render partial: "subscriptions/subscription_metadata_bar", locals: {
    document_subscription_count: @document_subscription_count,
    pi_subscription_count: @pi_subscription_count
  } %>
<% end %>

<div class="subscription-actions">
  <div class="subscription-type-filter">
    <ul>
      <script type="text/javascript" nonce="<%= content_security_policy_nonce %>">
        var subscriptionTypeFilters = <%= current_user.confirmed? ? @subscriptions.map{|s| s.type.underscore.dasherize}.uniq.to_json.html_safe : {}.to_json %>;
      </script>

      <li class="sub_document first" data-filter-doc-type="document"
        data-filter-doc-type-display="Document">

        <%= fr_icon 'document_subscription' %>
        <div class="label">Document</div>
      </li>

      <li class="sub_pi last" data-filter-doc-type="public-inspection-document"
        data-filter-doc-type-display="Public Inspection Document">

        <%= fr_icon 'pi_subscription' %>
        <div class="label">Public Inspection</div>
      </li>
    </ul>
  </div>
</div>

<% if current_user.confirmed? %>
  <% if @subscriptions.present? %>
    <ul class="subscriptions small_content_wrapper">
      <%= render partial: 'subscription_list_item', collection: @subscriptions,
        as: :subscription %>
    </ul>
  <% else %>
    <%= render partial: 'subscriptions/messages/no_subscriptions' %>
  <% end %>
<% else %>
    <%= render partial: 'subscriptions/messages/not_confirmed' %>
<% end %>

app/views/subscriptions/invalid_subscription.html.erb
<h3>Unable to subscribe</h3>

<p>We're sorry, the filters in this subscription are invalid.</p>

app/views/subscriptions/unsubscribe.html.erb
<% page_title 'Subscriptions' %>

<% title do %>
  <%= fr_icon 'document_subscription' %>
  <%= 'Subscriptions' %>
<% end %>

<%= bootstrap_context_wrapper do %>
  <div class="row">
    <div class="<%= bootstrap_col(xs: 12, md:12) %>">

      <div class="warning">
        <p class="errors_header">
          Are you sure you wish to unsubscribe <%= h @subscription.user.email %> from
          <%= link_to h(@subscription.mailing_list.title), documents_search_path(:conditions => @subscription.mailing_list.parameters) %>?
        </p>
      </div>

      <%= form_for(@subscription, url: suspend_subscription_path(@subscription.token), method: 'GET', authenticity_token: false) do |f| %>
        <%= f.submit 'Unsubscribe', class: 'btn fr_button secondary medium' %>
      <% end %>

    </div>
  </div>
<% end %>

app/views/subscriptions/unsubscribed.html.erb
<% page_title 'Unsubscribe' %>

<% title do %>
  <%= fr_icon 'document_subscription' %>
  <%= 'Subscriptions' %>
<% end %>

<%= bootstrap_context_wrapper do %>
  <div class="row">
    <div class="<%= bootstrap_col(xs: 12, md:12) %>">
      <p>You have been successfully unsubscribed from that search result.</p>
    </div>
  </div>
<% end %>