config/routes.rb
Rails.application.routes.draw do
  get 'error_page', to: 'special#error_page' unless Rails.env.production?

  if Rails.env.development?
    mount FRMailer::Preview => 'fr_mail_view'
    mount SubscriptionMailer::Preview => 'subscription_mail_view'
    mount CommentMailer::Preview => 'comment_mail_view'
    mount DocumentMailer::Preview => 'document_mail_view'
  end

  get 'alive' => 'special#alive'
  get 'status', to: 'special#status'

  get '/robots.txt', to: 'special#robots'

  match '/404', to: 'application#not_found', via: :all, as: :not_found
  match '/405', to: 'application#not_authorized', via: :all, as: :not_authorized
  match '/500', to: 'application#server_error', via: :all, as: :server_error

  #
  # Documents
  #

  get 'documents/current',
    to: "document_issues#current",
    as: :current_document_issue

  get 'documents/:year/:month/:day',
    to: "document_issues#show",
    as: :document_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'document_issues/search',
    to: "document_issues#search",
    as: :document_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }

  get 'documents/:document_number/emails/new',
    to: 'documents/emails#new',
    as: :new_document_email

  post 'documents/:document_number/emails',
    to: 'documents/emails#create',
    as: :document_email

  get 'documents/:year/:month/:day/:document_number/:slug',
    to: "documents#show",
    as: :document,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/,
      slug:  /[^\/]+/
    }

  # don't break old urls
  get '/a/:document_number(/:anchor)',
    to: "documents#tiny_url"

  get '/d/:document_number(/:anchor)',
    to: "documents#tiny_url",
    as: :short_document


  #
  # Documents Search
  #

  get 'documents/search',
    to: 'search/documents#show',
    as: 'documents_search'

  with_options(:quiet => true) do |js|
    js.get 'documents/search/count',
      to: 'search/documents#search_count',
      as: 'documents_search_search_count'
  end

  #
  # Public Inspection Documents
  #

  # legacy route that redirects to current
  get 'public-inspection',
    to: 'public_inspection_document_issues#public_inspection',
    as: :public_inspection

  get 'public-inspection/current',
    to: "public_inspection_document_issues#current",
    as: :current_public_inspection_issue

  get 'public-inspection/:year/:month/:day',
    to: "public_inspection_document_issues#show",
    as: :public_inspection_issue,
    constraints: {
      year:  /\d{4}/,
      month: /\d{1,2}/,
      day:   /\d{1,2}/
    }

  get 'public_inspection_issues/search',
    to: "public_inspection_document_issues#search",
    as: :public_inspection_issues_search,
    constraints: {
      date:  /\d{1,2}\/\d{1,2}\/\d{4}/
    }


  #
  # Public Inspection Documents Search
  #

  get 'public-inspection/search',
    to: 'search/public_inspection_documents#show',
    as: 'public_inspection_search'

  with_options(:quiet => true) do |js|
    js.get 'public-inspection/search/count',
      to: 'search/public_inspection_documents#search_count',
      as: 'public_inspection_search_count'
  end

  get 'public_inspection_documents/:year/:month/:day/:document_number/:slug',
    to: redirect('/public-inspection/%{document_number}/%{slug}')
  get 'public-inspection/:document_number/:slug',
    to: "public_inspection_documents#show",
    as: :public_inspection_document,
    constraints: {
      slug:  /[^\/]+/
    }

  #
  # Citations
  #

  get 'select-citation/:year/:month/:day/:citation',
    to: 'citations#cfr',
    as: 'select_cfr_citation',
    constraints: {
      citation: /\d+-CFR-\d+(?:\.\d+)?/,
      year: /\d{4}/,
      month: /\d{1,2}/,
      day: /\d{1,2}/
    }

  get 'citation/:volume-FR-:page',
    as: 'citation',
    to: 'citations#fr',
    contraints: {volume: /\d+/, page: /\d+/}

  get 'executive-order/:eo_number',
    as:'executive_order',
    to: 'citations#eo',
    contraints: {eo_number: /\d+/}


  #
  # ESI Routes
  #
  with_options(:quiet => true) do |esi|
    #CALENDAR
    esi.get 'esi/document_issues/:year/:month',
      to: 'document_issues#by_month',
      as: :document_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    esi.get 'esi/public_inspection_issues/:year/:month',
      to: 'public_inspection_document_issues#by_month',
      as: :public_inspection_issues_by_month,
      constraints: {
        :year        => /\d{4}/,
        :month       => /\d{1,2}/
      }

    # HEADER
    esi.get '/esi/special/csrf_protection',
      to: 'special#csrf_protection',
      as: :csrf_protection

    esi.get 'special/site_notifications/:identifier',
      to: 'special#site_notifications',
      as: :site_notification

    # READER AIDS
    esi.get 'esi/reader_aids/:section',
      to: 'reader_aids#index_section',
      as: :reader_aids_index_section,
      constraints: {
        section: /(#{ReaderAid::SECTIONS.map{|k,v| k}.join('|')})/
      }


    # FOOTER
    esi.get 'esi/layout/footer',
      to: 'special#footer',
      as: :footer
  end


  #
  # Reader Aids
  #

  get 'reader-aids',
    to: 'reader_aids#index',
    as: :reader_aids

  get 'reader-aids/search',
    to: 'reader_aids#search',
    as: :reader_aids_search

  get 'reader-aids/office-of-the-federal-register-blog',
    to: redirect("reader-aids/office-of-the-federal-register-announcements")

  get 'reader-aids/office-of-the-federal-register-blog/(*all)',
    to: redirect("reader-aids/office-of-the-federal-register-announcements/%{all}")

  get 'reader-aids/:section',
    to: 'reader_aids#section',
    as: :reader_aids_section

  get 'reader-aids/:section/*date/:page',
    to: 'reader_aids#show',
    as: :reader_aid_blog_post,
    contraints: {
      section: ['office-of-the-federal-register-announcements', 'recent-updates']
    }

  get 'reader-aids/:section/:page(/*subpage)',
    to: 'reader_aids#show',
    as: :reader_aid

  get '/policy/continuity-information', to: redirect('https://www.archives.gov/federal-register/write/newsletter/2024-may')


  #
  # Home
  #
  root to: 'special#home'


  #
  # Topics
  #

  get 'topics/suggestions',
    controller: "topics",
    actions: "suggestions",
    as: 'topics_suggestions'

  resources :topics, only: [:index, :show]

  get 'topics/:id/significant.:format',
    :controller => "topics",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_topic'


  #
  # Agencies
  #

  get 'agencies/suggestions',
    controller: "agencies",
    actions: "suggestions",
    as: 'agency_suggestions'

  resources :agencies, only: [:index, :show]

  get 'agencies/:id/significant.:format',
    :controller => "agencies",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_agency'


  #
  # Executive Orders
  #

  get '/executive-orders',
    to: redirect('/presidential-documents/executive-orders')

  get '/executive-orders/:president/:year',
    to: redirect('/presidential-documents/executive-orders/%{president}/%{year}')


  #
  # Presidential Documents
  #

  get '/presidential-documents',
    to: 'presidential_documents#index',
    as: :all_presidential_documents

  get '/presidential-documents/:type',
    to: 'presidential_documents#show',
    as: :presidential_documents,
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }

  get '/presidential-documents/:type/:president/:year',
    to: 'presidential_documents#by_president_and_year',
    as: 'presidential_documents_by_president_and_year',
    constraints: {
      type: Regexp.new("other-presidential-documents|executive-orders|proclamations")
    }


  #
  # Sections
  #

  get '/:section',
    to: 'sections#show',
    as: :section,
    constraints: {
      section: Regexp.new(Section.slugs.join("|"))
    }

  get 'sections/:id/significant.:format',
    :controller => "sections",
    :action => "significant_entries",
    :conditions => { :method => :get },
    as: 'significant_entries_section'


  #
  # Single Sign On
  #

  get '/auth/sign_in', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy', as: :sign_out


  #
  # API
  #
  scope "api" do
    namespace :v1 do
      resources :clippings, only: [:index]
    end
  end

  #
  # API Documentation
  #
  get '/developers/documentation/api/v1', to: 'api_documentation#show', as: :api_documentation

  get "/suggestions", to: "suggestions#index", as: :suggestions


  #
  # Suggested searches
  #

  get '/:slug',
    to: 'suggested_searches#show',
    as: :suggested_search,
    constraints: SuggestedSearchContraint.new


  #
  # FR Index
  #

  get '/index/:year',
    controller: "indexes",
    action: "year",
    as: 'index_year',
    constraints: {
      year: /(19|20)\d{2}/
    }

  get '/index/:year/:agency_slug',
    controller: "indexes",
    action: "year_agency",
    as: 'year_agency_index',
    constraints: {
      year: /(19|20)\d{2}/
    }

  resources :zendesk_tickets, only: [:create]

  #
  # My FR
  #

  scope 'my' do
    root :to => "clippings#index",
         :as => :my_root

    resources :clippings do
      collection do
        post 'bulk_create'
      end
    end

    get 'folders/my-clippings', to: redirect('/my/clippings')
    resources :folders
    resources :folder_clippings do
      collection do
        post 'delete'
      end
    end

    resources :comments, :only => [:index] do
      collection do
        post :persist_for_login
      end
    end

    get 'documents/:document_number/comments/new' => 'comments#new',
     :as => :new_comment
    post 'documents/:document_number/comments' => 'comments#create',
     :as => :comment

    resource :comment_publication_notifications,
      :only => [:create, :destroy]

app/controllers/special_controller.rb
class SpecialController < ApplicationController
  skip_before_action :authenticate_user!
  layout false, except: :home

  def csrf_protection
  end

  def home
    cache_for 1.day
  end

  def robots
    cache_for 1.day
    render 'robots', layout: false, content_type: 'text/plain'
  end

  def status
    render plain: "Serving requests (MyFR)"
  end

  # used by k8s probe to know when container
  # is ready / able to receive request
  def alive
    render json: {}.to_json, status: :ok
  end

  def site_notifications
    cache_for 1.day
    raw_response = HTTParty.get(
      "#{Settings.services.fr.api_core.internal_base_url}/site_notifications/#{params[:identifier]}"
    )
    if (raw_response.code == 200) && raw_response.parsed_response.present?
      @response = raw_response.parsed_response
    else
      head :ok
    end
  end

  def footer
    cache_for 1.day

    @reader_aids_sections = ReaderAidsPresenter::Base.new.sections
    @my_fr_presenter = MyFrPresenter.new
    @sections = Section.all

    render "layouts/footer"
  end

  def error_page
    render template: 'errors/500', layout: 'minimal'
  end
end

app/views/special/_account_needed_modal.html.erb
<div id="account-needed-modal">
  <a href="#" class="jqmClose">Close</a>

  <h3 class="title_bar">Account Required</h3>
  <p>
    Please <%= link_to 'sign in', new_user_session_path %> or
    <%= link_to 'create an account', new_user_registration_path %> to
    use this functionality.
  </p>
</div>

app/views/special/_late_issue.html.erb
<div class="row fr-head-metadata-bar fr-head-metadata-bar-official">
  <div class="<%= bootstrap_col(xs: 3, md: 3) %> fr-head-meta-label-holder">
    <div class="fr-head-meta-label">
      <i class="icon-fr2-calendar-alt"></i>
      <h4>
        <%= link_to 'Current Issue', current_document_issue_path %>
      </h4>
    </div>
  </div>

  <div class="<%= bootstrap_col(xs: 9, md: 9) %> fr-head-meta-counts">
    <p>
      Today's issue is currently unavailable; we apologize for any inconvenience.
      <%= link_to 'Browse other dates.', current_document_issue_path %>
    </p>
  </div>
</div>

app/views/special/_metadata_bar.html.erb
<!-- issue document metadata -->
<div class="row">
  <div class="fr-head-metadata-bar fr-head-metadata-bar-official">
    <div class="col-xs-3 col-md-3 fr-head-meta-label-holder">
      <div class="fr-head-meta-label">
        <i class="icon-fr2-calendar-alt"></i>
        <h4> <%= link_to "Current Issue", documents_search_path(:conditions => {
               :publication_date => {:is => Date.current}
             }) %> </h4>
      </div>
    </div>
    <div class="col-xs-9 col-md-9 fr-head-meta-counts">
      <ul class="inline-list">

          <% if @doc_presenter.any_document_counts?%>
            <% @doc_presenter.document_counts.each do |doc_type| %>
            <li>
              <%= link_to "#{doc_type.count} #{doc_type.name.pluralize(doc_type.count)}", documents_search_path(doc_type.search_conditions) %>
            </li>
            <% end %>
          <% else %>
            <li> No documents published today</li>
          <% end %>

          <li>
            <%= link_to_unless @doc_presenter.significant_documents.count == 0,
              "#{@doc_presenter.significant_documents.count.to_s} #{'Significant Document'.
                pluralize(@doc_presenter.significant_documents.count)}",
              documents_search_path(@doc_presenter.significant_documents.search_conditions) %>
          </li>

        <li><strong>?</strong> Pages</li>
        <li class="right">
          <a href=""
            class="link public-inspection-toggle toggle"
            data-toggle-target="#pi-metadata-bar"
            data-toggle-trigger="click">
            <i class="icon-fr2 icon-fr2-clipboard public-inspection"></i>
            <span class="link-text">View Public Inspection</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="clearfix"></div>
  </div>
</div>

<!-- issue public inspection metadata -->
<div id="pi-metadata-bar" class="row">
  <div class="fr-head-metadata-bar fr-head-metadata-bar-public-inspection">
    <div class="col-xs-3 col-md-3 fr-head-meta-label-holder">
      <div class="fr-head-meta-label">
        <i class="icon-fr2-clipboard"></i>
        <h4><%= link_to "Public Inspection", home_reader_aids_path %></h4>
      </div>

      <span class="icon-fr2 icon-fr2-stop-hand"></span>
    </div>
    <div class="col-xs-9 col-md-9 fr-head-meta-counts">
      <div class="row">
        <div class="col-xs-6 col-md-6">
          <div class="description">
            <p>
              The <a href="">Public Inspection page</a> on FederalRegister.gov offers a
              preview of documents scheduled to appear in the next day's
              Federal Register issue. The Public Inspection page may also
              include documents scheduled for later issues, at the request
              of the issuing agency.
            </p>
            <p>
              <%= link_to "Learn more about public inspection here.", reader_aids_using_fr_path %>
            </p>
          </div>
        </div>

        <div class="col-xs-6 col-md-6">
          <ul class="fr-list with-stats">

            <% @pi_presenter.all_filings.each do |filing_type| %>
              <li>
                <h5><%= filing_type.name %></h5>
                <span>updated on <%= "#{filing_type.formatted_updated_at} TBD"  %></span>
                <div class="public-inspection-list-stats">
                  <%= link_to_unless filing_type.total_count==0, "#{filing_type.total_count} #{'documents'.pluralize(filing_type.total_count) }", documents_search_path(filing_type.total_count_search_conditions)  %> from TBD agencies
                  <div>
                    <% filing_type.counts_by_identifier.each do |doc_type| %>
                        <%= link_to documents_search_path(doc_type.search_conditions) do %>
                          <%= document_type_icon_with_count(doc_type.slug, doc_type.count) %>
                          <%= doc_type.count %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </li>
            <% end %>

          </ul>
        </div>
      </div>

    </div>

    <div class="clearfix"></div>
  </div>
</div>

app/views/special/_navigation.html.erb
<div class="nav <%= 'announcement-present' if Settings.feature_flags.announcements %>" id="navigation">
  <ul class="container">
    <li id='nav-hamburger' class="nav-hamburger">
      <%= link_to("#", class: "home mobile-only", 'aria-label' => 'Toggle Navigation Menu') do %>
        <%= svg_icon('hamburger') %>
      <% end %>
    </li>

    <li id="non-essential-nav">
      <ul>
        <li id='nav-home' class="nav-home">
          <%= link_to(root_path, class: "home", 'aria-label' => 'Home') do %>
            <%= fr_icon('home') %>
          <% end %>
        </li>

        <li>
          <%= link_to(root_path, class: "mobile-only top_nav", 'aria-label' => 'Home') do %>
            <%= fr_icon('home') %>
            Home
          <% end %>
        </li>

        <%= render partial: 'sections/navigation', locals: {
          presenters: Section.all.map do |section|
            SectionPagePresenter.new(section, DocumentIssue.current.publication_date)
          end
        } %>

        <%= render partial: 'special/navigation/browse' %>

        <%= render partial: 'special/navigation/search' %>

        <%= render partial: 'reader_aids/navigation', locals: {
          reader_aids_sections: ReaderAidsPresenter::Base.new.sections
        } %>

        <%= render partial: 'special/navigation/my_fr' %>

        <li>
          <%= link_to(nil, class: "mobile-only site-feedback-button top_nav", 'aria-label' => 'Site Feedback') do %>
            <%= fr_icon('Chat') %>
            Site Feedback
          <% end %>
        </li>
      </ul>
    </li>

    <li class="inline_search" data-controller="placeholder">
      <%= semantic_form_for 'conditions',
        as: :conditions,
        url: documents_search_path,
        html: {id: "nav-search", method: :get, class: "search-form"} do |f| %>

        <label for="conditions_term">Search the Federal Register</label>
        <%= f.text_field :term,
          class: 'search-term',
          placeholder: 'Search Documents',
          data: {
            action: "click->placeholder#suggestions"
          },
          "aria-label" => 'Search Documents' %>

        <%= f.button fr_icon('Search').html_safe,
          class: 'search-submit',
          id: 'conditions_submit',
          "aria-label" => 'Search' %>
      <% end %>
    </li>
  </ul>
</div>

app/views/special/_site_header.html.erb
<div class="logo <%= header_type %>">
  <div class="hgroup">
    <% title_text =
        case header_type
        when "official"
          "The Daily Journal of the United States Government"
        when "public-inspection"
          "Public Inspection :: Tomorrow's Documents, Today"
        when "reader-aids"
          "Reader Aids :: Insight Into the FR Ecosystem"
        end
    %>
    <a href="/" title="Federal Register Home - <%= title_text %>">
      <svg class="masthead">
        <use xlink:href="<%= asset_path("fr-mastheads.svg")%>#<%= header_type %>-masthead">
        </use>
      </svg>
    </a>
  </div>
</div>

app/views/special/csrf_protection.html.erb
<%# currently in an uncached ESI route that supports cookies (not dropped by
  Varnish) without the user cookie the tag will not be generated with the
  proper value %>
<%= csrf_meta_tags %>

app/views/special/home.html.erb
<% page_title "Home - #{DocumentIssue.current.publication_date.to_s(:formal_no_year)}" %>

<% title do %>
  <%= DocumentIssue.current.publication_date.to_s(:formal_no_year) %>
<% end %>

<%= bootstrap_context_wrapper do %>
  <div class="homepage-grid">
    <%= render partial: "issues/summary", locals: {
      presenter: IssueSummaryPresenter.new(location: "home")
    } %>

    <%= render partial: 'special/home/embedded_search' %>

    <div id="popular-and-presdoc-container">
      <%= render partial: 'special/home/popular_documents', locals: {
        presenter: PopularDocumentsPresenter.new
      } %>

      <%= render partial: 'presidential_documents/homepage', locals: {
        presenter: PresidentialDocumentsHomepagePresenter.new
      } %>
    </div>

    <%= render partial: "reader_aids/homepage", locals: {
      presenter: ReaderAidsPresenter::HomepagePresenter.new
    } %>
  </div>
<% end %>

app/views/special/robots.text.erb
<% if Settings.app.allow_bot_traffic %>
  Sitemap: https://www.federalregister.gov/sitemaps/sitemap.xml.gz

  User-Agent: *
  Disallow: /documents/current
  Disallow: /documents/email-a-friend

  Disallow: /articles/search
  Disallow: /documents/search
  Disallow: /public-inspection/search
  Disallow: /regulations/search

  Disallow: /my/
  Disallow: /auth/
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/special/robots.txt.erb
<% if Settings.feature_flags.allow_bot_traffic %>
  Sitemap: https://www.federalregister.gov/sitemaps/sitemap.xml.gz

  User-Agent: *
  Disallow: /documents/current
  Disallow: /documents/email-a-friend

  Disallow: /articles/search
  Disallow: /documents/search
  Disallow: /public-inspection/search
  Disallow: /regulations/search

  Disallow: /my/
  Disallow: /auth/
<% else %>
  User-Agent: *
  Disallow: /
<% end %>

app/views/special/site_notifications.html.erb
<div class="site-notification-text-wrapper <%= @response["notification_type"] %>">
  <p class='site-notification-text'>
    <%= sanitize @response["description"] %>
  </p>
</div>